import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter/services.dart' show Clipboard, ClipboardData;
import 'package:flutter_animate/flutter_animate.dart';
import 'package:provider/provider.dart';
import '../../services/api_service.dart';
import '../../models/itinerary.dart';
import '../../theme/app_theme.dart';
import '../../widgets/gradient_background.dart';
import '../../widgets/glass_card.dart';
import '../../widgets/toast_overlay.dart';
import 'day_detail_screen.dart';

class TripMetadata {
  final List<String> clusterIds;
  final String? tripType;
  final String? transportMode;
  final String? groupType;
  final double startLat;
  final double startLon;

  const TripMetadata({
    required this.clusterIds,
    this.tripType,
    this.transportMode,
    this.groupType,
    required this.startLat,
    required this.startLon,
  });
}

/// Shows either a freshly-generated [multiDay] itinerary or loads one by [itineraryId].
class TripOverviewScreen extends StatefulWidget {
  final MultiDayItinerary? multiDay;
  final String? itineraryId;
  final TripMetadata? metadata;

  const TripOverviewScreen({super.key, this.multiDay, this.itineraryId, this.metadata});

  @override
  State<TripOverviewScreen> createState() => _TripOverviewScreenState();
}

class _TripOverviewScreenState extends State<TripOverviewScreen> {
  MultiDayItinerary? _multiDay;
  SavedItinerary? _saved;
  bool _loading = true;
  bool _saving = false;
  bool _isSaved = false;

  @override
  void initState() {
    super.initState();
    if (widget.multiDay != null) {
      _multiDay = widget.multiDay;
      _loading = false;
    } else if (widget.itineraryId != null) {
      _loadSaved();
    } else {
      _loading = false;
    }
  }

  Future<void> _loadSaved() async {
    try {
      final api = context.read<ApiService>();
      final res = await api.get('/ai/itinerary/${widget.itineraryId}', auth: true);
      if (!mounted) return;
      final data = res['data'] as Map<String, dynamic>? ?? {};
      setState(() {
        _saved = SavedItinerary.fromJson(data);
        _isSaved = true;
        _loading = false;
      });
    } catch (_) {
      if (!mounted) return;
      setState(() => _loading = false);
      AppToast.error(context, 'Could not load itinerary');
    }
  }

  Future<void> _shareTrip() async {
    final days = _multiDay?.days ?? _saved?.daysData ?? [];
    final title = _saved?.title ?? 'My Cebu Trip';
    final buffer = StringBuffer();
    buffer.writeln('🗺️ $title');
    buffer.writeln('${_multiDay?.totalDays ?? _saved?.days ?? 0} day(s) · ${_multiDay?.totalStops ?? _saved?.stopCount ?? 0} stops');
    buffer.writeln();
    for (final day in days) {
      buffer.writeln('Day ${day.dayNumber}${day.clusterName != null ? ' — ${day.clusterName}' : ''}:');
      for (final s in day.stops) {
        buffer.writeln('  • ${s.destination.name}');
      }
    }
    buffer.writeln();
    buffer.writeln('Generated by AIRAT-NA');
    await Clipboard.setData(ClipboardData(text: buffer.toString()));
    if (mounted) AppToast.success(context, 'Trip summary copied to clipboard');
  }

  Future<void> _saveTrip() async {
    if (_isSaved || _multiDay == null) return;
    setState(() => _saving = true);

    String title = 'My Cebu Trip';
    if (mounted) {
      final ctrl = TextEditingController(text: title);
      final result = await showDialog<String>(
        context: context,
        builder: (ctx) => ContentDialog(
          title: const Text('Save Trip'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Give your trip a name:',
                  style: TextStyle(color: ctx.appColors.textMuted, fontSize: 13)),
              const SizedBox(height: 10),
              TextBox(controller: ctrl, placeholder: 'My Cebu Trip'),
            ],
          ),
          actions: [
            Button(child: const Text('Cancel'), onPressed: () => Navigator.pop(ctx)),
            FilledButton(
              child: const Text('Save'),
              onPressed: () => Navigator.pop(ctx, ctrl.text.trim()),
            ),
          ],
        ),
      );
      if (!mounted) return;
      if (result == null || result.isEmpty) {
        setState(() => _saving = false);
        return;
      }
      title = result;
    }

    try {
      final api = context.read<ApiService>();
      final md = widget.metadata;
      final body = {
        'title': title,
        'days': _multiDay!.totalDays,
        'cluster_ids': md?.clusterIds ?? [],
        'trip_type': md?.tripType,
        'transport_mode': md?.transportMode,
        'group_type': md?.groupType,
        'total_distance': _multiDay!.totalDistance,
        'estimated_time': _multiDay!.estimatedTotalTime,
        'estimated_cost': _multiDay!.estimatedCost,
        'days_data': _multiDay!.days.map((d) => {
          'dayNumber': d.dayNumber,
          'stops': d.stops.map((s) => {
            'destination': {'id': s.destination.id},
            'visit_duration': s.visitDuration,
          }).toList(),
        }).toList(),
      };
      await api.post('/ai/itinerary/save', body: body, auth: true);
      if (!mounted) return;
      setState(() { _isSaved = true; _saving = false; });
      AppToast.success(context, 'Trip saved!');
    } catch (_) {
      if (!mounted) return;
      setState(() => _saving = false);
      AppToast.error(context, 'Could not save trip');
    }
  }

  @override
  Widget build(BuildContext context) {
    final c = context.appColors;

    if (_loading) {
      return const GradientBackground(child: Center(child: ProgressRing()));
    }

    final days = _multiDay?.days ?? _saved?.daysData ?? [];
    final totalDays = _multiDay?.totalDays ?? _saved?.days ?? 0;
    final totalStops = _multiDay?.totalStops ?? _saved?.stopCount ?? 0;
    final totalDist = _multiDay?.totalDistance ?? _saved?.totalDistance ?? 0.0;
    final totalTime = _multiDay?.estimatedTotalTime ?? _saved?.estimatedTime ?? 0;
    final totalCost = _multiDay?.estimatedCost ?? _saved?.estimatedCost ?? 0.0;
    final title = _saved?.title ?? 'Your Cebu Trip';

    return GradientBackground(
      child: SafeArea(
        child: CustomScrollView(
          slivers: [
            // Header
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(20, 16, 20, 0),
                child: Row(
                  children: [
                    GestureDetector(
                      onTap: () => Navigator.pop(context),
                      child: Container(
                        width: 36, height: 36,
                        decoration: BoxDecoration(
                          color: c.surfaceElevated,
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: c.borderMedium),
                        ),
                        child: Icon(FluentIcons.chevron_left, size: 16, color: c.textMuted),
                      ),
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: Text(title,
                          style: TextStyle(fontSize: 20, fontWeight: FontWeight.w700, color: c.textStrong),
                          maxLines: 1, overflow: TextOverflow.ellipsis),
                    ),
                    GestureDetector(
                      onTap: _shareTrip,
                      child: Container(
                        width: 36, height: 36,
                        decoration: BoxDecoration(
                          color: c.surfaceElevated,
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: c.borderMedium),
                        ),
                        child: Icon(FluentIcons.share, size: 16, color: c.textMuted),
                      ),
                    ),
                    const SizedBox(width: 8),
                    if (!_isSaved)
                      _saving
                          ? const SizedBox(width: 32, height: 32, child: ProgressRing(strokeWidth: 3))
                          : GestureDetector(
                              onTap: _saveTrip,
                              child: Container(
                                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                                decoration: BoxDecoration(
                                  color: AppColors.red500,
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                child: const Text('Save',
                                    style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Colors.white)),
                              ),
                            ),
                    if (_isSaved)
                      Icon(FluentIcons.check_mark, size: 18, color: AppColors.green),
                  ],
                ).animate().fadeIn(duration: 400.ms),
              ),
            ),

            // Stats row
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(20, 16, 20, 0),
                child: GlassCard(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceAround,
                    children: [
                      _stat('$totalDays', totalDays == 1 ? 'Day' : 'Days', AppColors.red400, c),
                      _vDiv(c),
                      _stat('$totalStops', 'Stops', AppColors.blue, c),
                      _vDiv(c),
                      _stat('${totalDist.toStringAsFixed(1)}km', 'Dist', AppColors.green, c),
                      _vDiv(c),
                      _stat(_fmtMin(totalTime), 'Time', AppColors.purple, c),
                      _vDiv(c),
                      _stat('₱${totalCost.toStringAsFixed(0)}', 'Cost', AppColors.amber, c),
                    ],
                  ),
                ).animate().fadeIn(delay: 100.ms, duration: 400.ms),
              ),
            ),

            // Start Journey button
            if (days.isNotEmpty)
              SliverToBoxAdapter(
                child: Padding(
                  padding: const EdgeInsets.fromLTRB(20, 14, 20, 0),
                  child: SizedBox(
                    width: double.infinity,
                    child: FilledButton(
                      onPressed: () => Navigator.of(context).push(
                        FluentPageRoute(
                          builder: (_) => DayDetailScreen(day: days[0], allDays: days),
                        ),
                      ),
                      style: ButtonStyle(
                        backgroundColor: WidgetStateProperty.all(AppColors.green),
                        shape: WidgetStateProperty.all(
                            RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
                        padding: WidgetStateProperty.all(
                            const EdgeInsets.symmetric(vertical: 13)),
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: const [
                          Icon(FluentIcons.location, size: 16, color: Colors.white),
                          SizedBox(width: 8),
                          Text('Start Journey',
                              style: TextStyle(fontSize: 15, fontWeight: FontWeight.w700, color: Colors.white)),
                        ],
                      ),
                    ),
                  ).animate().fadeIn(delay: 150.ms, duration: 400.ms),
                ),
              ),

            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(20, 20, 20, 8),
                child: Text('Your Itinerary',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700, color: c.textStrong)),
              ),
            ),

            if (days.isEmpty)
              SliverToBoxAdapter(
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: GlassCard(
                    child: Center(
                      child: Text('No itinerary generated', style: TextStyle(color: c.textMuted)),
                    ),
                  ),
                ),
              )
            else
              SliverPadding(
                padding: const EdgeInsets.fromLTRB(20, 0, 20, 24),
                sliver: SliverList.separated(
                  itemCount: days.length,
                  separatorBuilder: (_, __) => const SizedBox(height: 12),
                  itemBuilder: (context, i) => _DayCard(day: days[i], allDays: days)
                      .animate()
                      .fadeIn(delay: (100 + i * 80).ms, duration: 400.ms),
                ),
              ),
          ],
        ),
      ),
    );
  }

  Widget _stat(String value, String label, Color color, AppColorScheme c) => Column(
    mainAxisSize: MainAxisSize.min,
    children: [
      Text(value, style: TextStyle(fontSize: 13, fontWeight: FontWeight.w800, color: color)),
      const SizedBox(height: 2),
      Text(label, style: TextStyle(fontSize: 10, color: c.textFaint)),
    ],
  );

  Widget _vDiv(AppColorScheme c) => Container(width: 1, height: 36, color: c.borderLight);

  String _fmtMin(int minutes) {
    if (minutes < 60) return '${minutes}m';
    final h = minutes ~/ 60;
    final m = minutes % 60;
    return m > 0 ? '${h}h${m}m' : '${h}h';
  }
}

class _DayCard extends StatelessWidget {
  final DayItinerary day;
  final List<DayItinerary> allDays;
  const _DayCard({required this.day, this.allDays = const []});

  @override
  Widget build(BuildContext context) {
    final c = context.appColors;
    return GestureDetector(
      onTap: () => Navigator.of(context).push(
        FluentPageRoute(builder: (_) => DayDetailScreen(day: day, allDays: allDays)),
      ),
      child: GlassCard(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: AppColors.red500,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text('Day ${day.dayNumber}',
                      style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Colors.white)),
                ),
                if (day.clusterName != null) ...[
                  const SizedBox(width: 8),
                  Text(day.clusterName!,
                      style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: c.textStrong)),
                ],
                const Spacer(),
                Icon(FluentIcons.chevron_right, size: 14, color: c.textFaint),
              ],
            ),
            const SizedBox(height: 10),
            Wrap(
              spacing: 8, runSpacing: 6,
              children: [
                _chip(FluentIcons.poi, '${day.stops.length} stops', AppColors.blue, c),
                if (day.estimatedTravelTime > 0)
                  _chip(FluentIcons.car, _fmtMin(day.estimatedTravelTime), AppColors.green, c),
                if (day.estimatedCost > 0)
                  _chip(FluentIcons.money, '₱${day.estimatedCost.toStringAsFixed(0)}', AppColors.amber, c),
              ],
            ),
            if (day.stops.isNotEmpty) ...[
              const SizedBox(height: 10),
              Text(
                day.stops.map((s) => s.destination.name).take(3).join(' → ') +
                    (day.stops.length > 3 ? ' +${day.stops.length - 3}' : ''),
                style: TextStyle(fontSize: 12, color: c.textMuted, height: 1.4),
                maxLines: 2, overflow: TextOverflow.ellipsis,
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _chip(IconData icon, String label, Color color, AppColorScheme c) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
    decoration: BoxDecoration(color: color.withAlpha(20), borderRadius: BorderRadius.circular(6)),
    child: Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(icon, size: 10, color: color),
        const SizedBox(width: 4),
        Text(label, style: TextStyle(fontSize: 10, color: color, fontWeight: FontWeight.w500)),
      ],
    ),
  );

  String _fmtMin(int minutes) {
    if (minutes < 60) return '${minutes}m';
    final h = minutes ~/ 60;
    final m = minutes % 60;
    return m > 0 ? '${h}h ${m}m' : '${h}h';
  }
}
